set(solver_LIBRARIES
    ${PROJECT_SOURCE_DIR}/Solver/lib/libSolver.so
)
set(solver_INCLUDE_DIRS
    ${PROJECT_SOURCE_DIR}/Solver/include
)
set(solver_SOURCES
    src/forces_solver_interface.cpp
    Solver/include/mpc_planner_generated.cpp
    Solver/Solver_interface.c
    Solver/Solver_model.c
)
